config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :subcommunities do
    resources :subscriptions, only: %i[create destroy]
    resources :posts, only: %i[new create edit update show destroy] do
      resources :comments, only: %i[create edit update destroy]
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :message, presence: true

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  belongs_to :user
  belongs_to :subcommunity

  has_many :comments, dependent: :destroy
end

app/models/subcommunity.rb
class Subcommunity < ApplicationRecord
  validates :title, presence: true
  validates :slogan, presence: true

  belongs_to :user

  has_many :subscriptions, dependent: :destroy
  has_many :posts, dependent: :destroy
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :subcommunity
end

app/models/user.rb
class User < ApplicationRecord
  has_many :subcommunities, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscribed_subcoms, through: :subscriptions, source: :subcommunity, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def subscribed?(subcommunity)
    subscribed_subcoms.include?(subcommunity)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_not_found
    render plain: 'Not found :(', status: :not_found
  end

  def render_forbidden
    render text: 'Not Allowed >:O', status: :forbidden
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @subcom = Subcommunity.find(params[:subcommunity_id])
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params.merge(user: current_user))

    redirect_to subcommunity_post_path(@subcom, @post)
  end

  def update
    @subcom = Subcommunity.find(params[:subcommunity_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    return render_not_found if @comment.blank?
    return render_forbidden if @comment.user != current_user
    @comment.update_attributes(comment_params)

    redirect_to subcommunity_post_path(@subcom, @post)
  end

  def destroy
    @subcom = Subcommunity.find(params[:subcommunity_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    return render_not_found if @comment.blank?
    return render_forbidden if @comment.user != current_user
    @comment.destroy
    redirect_to subcommunity_post_path(@subcom, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]

  def new
    @subcom = Subcommunity.find_by(id: params[:subcommunity_id])
    @post = Post.new
  end

  def create
    @subcom = Subcommunity.find_by(id: params[:subcommunity_id])
    @subcom.posts.create(post_params.merge(user: current_user))

    redirect_to subcommunity_path(@subcom)
  end

  def show
    @subcom = Subcommunity.find_by(id: params[:subcommunity_id])
    @post = Post.find_by(id: params[:id])
    return render_not_found if @post.blank?
    @comment = Comment.new
  end

  def edit
    @subcom = Subcommunity.find_by(id: params[:subcommunity_id])
    @post = Post.find(params[:id])
    return render_not_found if @post.blank?
    return render_forbidden if @post.user != current_user
  end

  def update
    @subcom = Subcommunity.find_by(id: params[:subcommunity_id])
    @post = Post.find(params[:id])
    return render_not_found if @post.blank?
    return render_forbidden if @post.user != current_user

    @post.update_attributes(post_params)
    redirect_to subcommunities_path
  end

  def destroy
    @post = Post.find(params[:id])
    return render_not_found if @post.blank?
    return render_forbidden if @post.user != current_user
    @post.destroy
    redirect_to subcommunities_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @posts = Post.all
    @subcom = Subcommunity.find_by(params[:subcommunity_id])
  end
end

app/controllers/subcommunities_controller.rb
class SubcommunitiesController < ApplicationController
  before_action :authenticate_user!, only: %i[create new edit update destroy]

  def index
    @subcom = Subcommunity.all
  end

  def new
    @subcom = Subcommunity.new
  end

  def create
    @subcom = current_user.subcommunities.create(subcom_params)
    if @subcom.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @subs = Subscription.find_by(id: params[:subscription_id])
    @subcom = Subcommunity.find_by(id: params[:id])
    return render_not_found if @subcom.blank?
  end

  def edit
    @subcom = Subcommunity.find_by(id: params[:id])
    return render_not_found if @subcom.blank?
    return render_forbidden if current_user != @subcom.user
  end

  def update
    @subcom = Subcommunity.find_by(id: params[:id])
    return render_forbidden if @subcom.user != current_user
    @subcom.update_attributes(subcom_params)
    redirect_to subcommunities_path
  end

  def destroy
    @subcom = Subcommunity.find_by(id: params[:id])
    return render_forbidden if @subcom.user != current_user
    @subcom.destroy
    redirect_to root_path
  end

  private

  def subcom_params
    params.require(:subcommunity).permit(:title, :slogan)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.subscriptions.create(subcommunity: current_subcom)
    redirect_to subcommunity_path(current_subcom)
  end

  def destroy
    @subs = Subscription.find(params[:id])
    @subscribed.destroy
    redirect_to subcommunity_path(current_subcom)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_subscription
  #   @subscription = Subscription.find(params[:id])
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  # def subscription_params
  #   params.require(:)
  # end

  def current_subcom
    @current_subcom ||= Subcommunity.find(params[:subcommunity_id])
  end

  def current_subscription
    @current_subs ||= Subscription.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subcommunities_helper.rb
module SubcommunitiesHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Community</title>
    <%= csrf_meta_tags %>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-toggleable-md navbar-light">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon my-toggler"></span>
      </button>
      <%= link_to 'Community', root_path, class: 'navbar-brand' %>
      <div class="collapse navbar-collapse" id='navbarSupportedContent'>
        <ul class="mr-auto navbar-nav">
          <li class="nav-item active">
            <%= link_to 'Subcommunities', subcommunities_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Create a new subcommunity',new_subcommunity_path, class: 'nav-link' %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item active">
             <%= link_to 'Profile', user_path(current_user), class: 'nav-link' %>
            </li>
            <li class="nav-item">
             <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="text-center alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="text-center alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <br />
  </body>
</html>

app/views/posts/edit.html.erb
<div class="booyah-box">
  <h1> Edit Post </h1>
    <%= simple_form_for @post, url: subcommunity_post_path(@subcom) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.submit 'Update', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h2 class='text-center'>Create a New Post</h2>
    <%= simple_form_for @post, url: subcommunity_posts_path(@subcom) do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.submit 'Create', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="booyah-box container">
  <h1><%= @post.title %></h1>
  <h4><%= @post.description %></h3>
  <hr />
  <% if @post.user.present? %>
    <small> - <%=@post.user.email%></small>
  <% end %>
  <% if current_user && current_user == @post.user %>
    <%= link_to 'Edit', edit_subcommunity_post_path(@subcom, @post), class: 'btn btn-primary btn-sm' %>
    <%= link_to 'Destroy', subcommunity_post_path(@subcom, @post), method: :delete, data: { confirm: "Are you sure you want to delete"} , class: 'btn btn-danger btn-sm' %>
  <% end %>
  <br />
  <br />
  <!-- Button trigger modal for Creating a comment-->
  <button type="button" class="btn btn-primary btn-md" data-toggle="modal" data-target="#myModal">
    Add a Comment
  </button>
  <br />
  <br />
  <div class="booyah-box">
    <% @post.comments.each do |comment| %>
      <p><%=comment.message %>
        <!-- Button trigger modal for editing/updating comments-->
        <% if comment.user.present? %>
          <small> - <%=comment.user.email%></small>
        <% end %>
        <% if current_user && current_user == comment.user %>
          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal2">
            Edit
          </button>
          <%= link_to 'Destroy', subcommunity_post_comment_path(@subcom, @post, comment), method: :delete, data: { confirm: "Are you sure you want to delete"} , class: 'btn btn-danger btn-sm' %>
        <% end %>
      </p>
      <hr />
      <!-- Modal for updating comments -->
      <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel2" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
              <h4 class="modal-title" id="myModalLabel2">
                Edit Comment</h4>
              <%= simple_form_for comment, url: subcommunity_post_comment_path(@subcom, @post, comment) do |f| %>
                <div class="modal-body">
                  <%= f.input :message %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <%= f.submit "Update", class: 'btn btn-primary' %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- end of modal -->
    <% end %>
  </div>
</div>

<!-- Modal for Creating comments -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">
          Add a Comment</h4>
        </div>
        <%= simple_form_for @comment, url: subcommunity_post_comments_path(@subcom, @post) do |f| %>
        <div class="modal-body">
          <%= f.input :message %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <%= f.submit "Add a Comment", class: 'btn btn-primary' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- end of modal -->

app/views/static_pages/index.html.erb
<div class="container">
  <h1 class='text-center'>Welcome to Community</h1>
  <br />
  <div class='booyah-box offset-1 col-10'>
    <% @posts.each do |post| %>
      <p>
        <%= link_to post.title, subcommunity_post_path(@subcom, post) %>
        <% if post.user.present? %>
          <small> -<%= post.user.email%></small>
        <% end %>
      </p>
      <hr />
    <% end %>
  </div>
</div>

app/views/subcommunities/edit.html.erb
<div class="booyah-box">
  <h2 class="text-center">Edit your subcommunity</h2>
    <%= simple_form_for @subcom do |f| %>
    <%=f.input :title %>
    <%= f.input :slogan %>
    <%= f.submit 'Update', class: 'btn btn-success' %>
  <%end %>
</div>

app/views/subcommunities/index.html.erb
<div class='booyah-box container'>
<br />
<h1 class='text-center'>Check out the cool Subcommunities</h1>
<br />
  <% @subcom.each do |sub| %>
    <div class='booyah-box'>
      <h2><%=link_to sub.title, subcommunity_path(sub) %></h2>
      <h3><%=sub.slogan%></h3>
      <% if current_user && current_user == sub.user %>
      <%= link_to 'Edit', edit_subcommunity_path(sub), class: 'btn btn-primary' %>
      <%= link_to 'Destroy', subcommunity_path(sub), method: :delete, data: { confirm: "Are you sure you want to delete"} , class: 'btn btn-danger' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/subcommunities/new.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h2 class="text-center">Create a new sub community</h2>
    <%= simple_form_for @subcom do |f| %>
    <%= f.input :title %>
    <%= f.input :slogan %>
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/subcommunities/show.html.erb
<div class='booyah-box offset-1 col-10'>
  <h1>Subcommunity for <span><%= @subcom.title %></span></h1>
  <h2><%=@subcom.slogan%></h2>
  <% if current_user && current_user.subscribed?(@subcom) %>
    <h3 class='badge badge-info'>Subscribed!</h3>
  <% else %>
    <%= link_to 'Subscribe', subcommunity_subscriptions_path(@subcom), class: 'btn btn-success btn-sm', method: :post %>
  <% end %>
  <%= link_to 'Unsub', subcommunity_subscriptions_path(@subcom, @subs), class: 'btn btn-info', data: { confirm: 'Are you sure?' }, method: :destroy %>
  <br />
  <br />
  <%= link_to 'Add a Post', new_subcommunity_post_path(@subcom), class: 'btn btn-primary btn-small' %>
  <br />
  <div class='booyah-box'>
    <h2>Posts</h2>
    <br />
    <% @subcom.posts.each do |post| %>
      <h3><%=link_to post.title, subcommunity_post_path(@subcom, post) %>
        <span>
          <% if post.user.present? %>
            <small class='username-text'> - <%= post.user.email %></small>
          <% end %>
        </span>
      </h3>
      </p>
      <hr />
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="text-center">User Profile Page </h1>
  <br />
  <div class="booyah-box">
    <h2>Subcribed Subcommunities</h2>
    <% current_user.subscribed_subcoms.each do |subscribed| %>
      <p><%= link_to subscribed.title, subcommunity_path(subscribed) %>
      </p>
    <% end %>
  </div>
  <div class="booyah-box">
    <h2>Subcommunities Created</h2>
    <% current_user.subcommunities.each do |subcom| %>
      <%= link_to subcommunity_path(subcom) do %>
        <p><%= subcom.title %> - <span><%=subcom.slogan%></span></p>
      <% end %>
    <% end %>
  </div>
  <div class="booyah-box">
  <h2>Posts</h2>
    <% current_user.posts.each do |post| %>
      <%= link_to subcommunity_post_path(post.subcommunity, post) do %>
        <p><%= post.title %> - <span><%=post.description%></span></p>
      <%end%>
    <% end %>
  </div>

  <div class="booyah-box">
    <h2>Comments</h2>
    <% current_user.comments.each do |comment| %>
      <%= link_to subcommunity_post_path(comment.post.subcommunity, comment.post) do %>
        <p><%= comment.message %></p>
      <%end%>
    <% end %>
  </div>
</div>